openapi: 3.0.0
info:
  title: Medusa Reviews API
  description: API for managing product reviews in a Medusa e-commerce store
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Example server

paths:
  /store/reviews:
    post:
      summary: Create a new product review
      operationId: createReview
      tags:
        - reviews
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReviewInput'
      responses:
        '200':
          description: Review created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateReviewOutput'

  /store/products/reviews:
    get:
      summary: List reviews
      operationId: listReviews
      tags:
        - reviews
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/order'
        - name: product_ids
          in: query
          description: Filter reviews by product IDs
          schema:
            type: array
            items:
              type: string
        - name: my_reviews_only
          in: query
          description: Show only reviews created by the current customer
          schema:
            type: boolean
        - name: verified_purchase_only
          in: query
          description: Show only reviews from verified purchases
          schema:
            type: boolean
        - name: rating
          in: query
          description: Filter reviews by rating
          schema:
            type: integer
            minimum: 1
            maximum: 5
        - name: include_product
          in: query
          description: Include product details in the response
          schema:
            type: boolean
      responses:
        '200':
          description: Reviews retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListReviewsOutput'

  /store/reviews/product/{product_id}:
    parameters:
      - name: product_id
        in: path
        required: true
        description: The ID of the product
        schema:
          type: string
    get:
      summary: List reviews for a specific product
      operationId: listProductReviews
      tags:
        - reviews
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/order'
        - name: my_reviews_only
          in: query
          description: Show only reviews created by the current customer
          schema:
            type: boolean
        - name: verified_purchase_only
          in: query
          description: Show only reviews from verified purchases
          schema:
            type: boolean
        - name: sort
          in: query
          description: Field to sort by
          schema:
            type: string
            enum: [created_at, rating]
        - name: order
          in: query
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
        - name: rating
          in: query
          description: Filter reviews by rating
          schema:
            type: integer
            minimum: 1
            maximum: 5
        - name: include_product
          in: query
          description: Include product details in the response
          schema:
            type: boolean
      responses:
        '200':
          description: Product reviews retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListProductReviewsOutput'

  /store/reviews/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The ID of the review
        schema:
          type: string
    delete:
      summary: Delete a review
      operationId: deleteReview
      tags:
        - reviews
      responses:
        '200':
          description: Review deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteReviewOutput'

  /store/reviews/product/{product_id}/aggregate-counts:
    parameters:
      - name: product_id
        in: path
        required: true
        description: The ID of the product
        schema:
          type: string
    get:
      summary: Get aggregate review counts for a product
      operationId: aggregateCounts
      tags:
        - reviews
      parameters:
        - name: verified_purchase_only
          in: query
          description: Include only reviews from verified purchases
          schema:
            type: boolean
      responses:
        '200':
          description: Aggregate counts retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregateCountsOutput'

components:
  parameters:
    limit:
      name: limit
      in: query
      description: The maximum number of items to retrieve
      schema:
        type: integer
        default: 10
    offset:
      name: offset
      in: query
      description: The number of items to skip before retrieving the returned items
      schema:
        type: integer
        default: 0
    order:
      name: order
      in: query
      description: The field to sort by and in which order (e.g., -created_at)
      schema:
        type: string

  schemas:
    PaginatedInput:
      type: object
      properties:
        limit:
          type: integer
          description: The maximum number of items to retrieve
        offset:
          type: integer
          description: The number of items to skip before retrieving the returned items
        order:
          type: string
          description: The field to sort by and in which order (e.g., -created_at)

    PaginatedOutputMeta:
      type: object
      properties:
        totalPages:
          type: integer
          description: Total number of pages
        currentPage:
          type: integer
          description: Current page number
        nextPage:
          type: integer
          description: Next page number
        prevPage:
          type: integer
          description: Previous page number
        skip:
          type: integer
          description: Number of items skipped
        take:
          type: integer
          description: Number of items taken
        count:
          type: integer
          description: Total number of items

    # External types from @medusajs/types
    CustomerDTO:
      type: object
      description: Customer data transfer object from @medusajs/types

    ProductDTO:
      type: object
      description: Product data transfer object from @medusajs/types

    AggregateCounts:
      type: object
      required:
        - average
        - counts
        - product_id
        - total_count
      properties:
        average:
          type: number
          description: Average rating for the product
        counts:
          type: array
          description: Counts of reviews grouped by rating
          items:
            type: object
            properties:
              rating:
                type: number
                description: Rating value
              count:
                type: integer
                description: Number of reviews with this rating
        product_id:
          type: string
          description: ID of the product
        total_count:
          type: integer
          description: Total count of reviews for the product

    Review:
      type: object
      required:
        - id
        - title
        - content
        - rating
        - created_at
        - image_urls
        - is_verified_purchase
        - product_id
        - customer
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        rating:
          type: number
          minimum: 1
          maximum: 5
        created_at:
          type: string
          format: date-time
        image_urls:
          type: array
          items:
            type: string
            format: uri
        is_verified_purchase:
          type: boolean
        product_id:
          type: string
        customer:
          type: object
          properties:
            first_name:
              type: string
            last_name:
              type: string
        product:
          type: object
          nullable: true
          properties:
            id:
              type: string
            thumbnail:
              type: string
              nullable: true
            title:
              type: string
            handle:
              type: string
            average:
              type: number
            counts:
              type: array
              items:
                type: object
                properties:
                  rating:
                    type: number
                  count:
                    type: integer
            product_id:
              type: string
            total_count:
              type: integer

    CreateReviewInput:
      type: object
      required:
        - content
        - rating
        - product_id
        - image_base64s
      properties:
        content:
          type: string
          description: Review content
        rating:
          type: number
          minimum: 1
          maximum: 5
          description: Review rating
        product_id:
          type: string
          description: ID of the product being reviewed
        image_base64s:
          type: array
          description: Array of base64 encoded images
          items:
            type: string
            format: base64
        title:
          type: string
          description: Review title

    CreateReviewOutput:
      $ref: '#/components/schemas/Review'

    ListReviewsInput:
      allOf:
        - $ref: '#/components/schemas/PaginatedInput'
        - type: object
          properties:
            product_ids:
              type: array
              items:
                type: string
              description: Filter reviews by product IDs
            my_reviews_only:
              type: boolean
              description: Show only reviews created by the current customer
            verified_purchase_only:
              type: boolean
              description: Show only reviews from verified purchases
            rating:
              type: integer
              minimum: 1
              maximum: 5
              description: Filter reviews by rating
            include_product:
              type: boolean
              description: Include product details in the response

    ListReviewsOutput:
      allOf:
        - $ref: '#/components/schemas/PaginatedOutputMeta'
        - type: object
          required:
            - data
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/Review'

    ListProductReviewsInput:
      allOf:
        - $ref: '#/components/schemas/PaginatedInput'
        - type: object
          required:
            - product_id
          properties:
            product_id:
              type: string
              description: ID of the product
            my_reviews_only:
              type: boolean
              description: Show only reviews created by the current customer
            verified_purchase_only:
              type: boolean
              description: Show only reviews from verified purchases
            sort:
              type: string
              enum: [created_at, rating]
              description: Field to sort by
            order:
              type: string
              enum: [asc, desc]
              description: Sort order
            rating:
              type: integer
              minimum: 1
              maximum: 5
              description: Filter reviews by rating
            include_product:
              type: boolean
              description: Include product details in the response

    ListProductReviewsOutput:
      allOf:
        - $ref: '#/components/schemas/PaginatedOutputMeta'
        - type: object
          required:
            - data
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/Review'

    DeleteReviewInput:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: ID of the review to delete

    DeleteReviewOutput:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: ID of the deleted review

    AggregateCountsInput:
      type: object
      required:
        - product_id
      properties:
        product_id:
          type: string
          description: ID of the product
        verified_purchase_only:
          type: boolean
          description: Include only reviews from verified purchases

    AggregateCountsOutput:
      $ref: '#/components/schemas/AggregateCounts'
